repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: pdm run ruff
        args:
          - "--fix"
          - "--show-fixes"
        language: python
        types_or: [python, pyi]
        stages: ["push"]
      
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: pdm run black
        language: python
        types_or: [python, pyi]
        stages: ["push"] 